# -*- coding: utf-8 -*-
"""visuals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdMOn3e9lSC2A4tU22_L-eID3qMobmlu
"""

#I will be using google colab and drive to upload ans save my files

#Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

#Load Data
base_path = '/content/drive/MyDrive/visual/'

ms = pd.read_csv(base_path + 'mens_swimming.csv')
ws = pd.read_csv(base_path + 'womens_swimming.csv')
mv = pd.read_csv(base_path + 'mens_volleyball.csv')
wv = pd.read_csv(base_path + 'womens_volleyball.csv')

#Calculate Average Heights
avg_heights = {
    "Men's Swimming": ms['Height'].mean(),
    "Women's Swimming": ws['Height'].mean(),
    "Men's Volleyball": mv['Height'].mean(),
    "Women's Volleyball": wv['Height'].mean()
}

print("Average Heights (inches):")
for group, avg in avg_heights.items():
    print(f"{group}: {avg:.2f} in")

#Tallest and Shortest Output (top 5 + exact ties)
def get_extremes(df, group_name):
    max_height = df['Height'].max()
    min_height = df['Height'].min()
    tallest = df[df['Height'] == max_height]
    shortest = df[df['Height'] == min_height]
    top5_tallest = df.sort_values(by='Height', ascending=False).head(5)
    top5_shortest = df.sort_values(by='Height').head(5)

    print(f"\n {group_name} - Tallest ({max_height} in):")
    print(tallest[['Name', 'Height']])
    print(f"\n {group_name} - Shortest ({min_height} in):")
    print(shortest[['Name', 'Height']])

    return group_name, max_height, min_height, tallest, shortest, top5_tallest, top5_shortest

#Run and Save Outputs
groups = [("Men's Swimming", ms), ("Women's Swimming", ws),
          ("Men's Volleyball", mv), ("Women's Volleyball", wv)]

summary_lines = []

for group_name, df in groups:
    grp, max_h, min_h, tallest, shortest, top5_tall, top5_short = get_extremes(df, group_name)

    summary_lines.append(f"--- {group_name} ---\n")
    summary_lines.append(f"Average Height: {df['Height'].mean():.2f} in\n")

    summary_lines.append(f"Top 5 Tallest:\n{top5_tall[['Name', 'Height']].to_string(index=False)}\n")
    summary_lines.append(f"Top 5 Shortest:\n{top5_short[['Name', 'Height']].to_string(index=False)}\n")

    summary_lines.append(f"Tallest (Exact Matches):\n{tallest[['Name', 'Height']].to_string(index=False)}\n")
    summary_lines.append(f"Shortest (Exact Matches):\n{shortest[['Name', 'Height']].to_string(index=False)}\n\n")

# Save summary to text file
with open(base_path + 'height_summary.txt', 'w') as f:
    f.writelines('\n'.join(summary_lines))

#Bar Graph


plt.figure(figsize=(8,6))
plt.bar(avg_heights.keys(), avg_heights.values())
plt.ylabel("Average Height (inches)")
plt.title("Average Athlete Heights by Sport")
plt.xticks(rotation=15)
plt.tight_layout()
plt.savefig(base_path + "average_heights.png")
plt.show()